In [1]:
#Import Library Pandas
import pandas as pd

In [2]:
#load Data 
data_frame = pd.read_csv("test.csv")

#backup dataframe
data_frame_backup = data_frame

data_frame

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [3]:
#mencari mean
mean_data = data_frame.mean()
mean_data

Id               2190.000000
MSSubClass         57.378341
LotFrontage        68.580357
LotArea          9819.161069
OverallQual         6.078821
OverallCond         5.553804
YearBuilt        1971.357779
YearRemodAdd     1983.662783
MasVnrArea        100.709141
BsmtFinSF1        439.203704
BsmtFinSF2         52.619342
BsmtUnfSF         554.294925
TotalBsmtSF      1046.117970
1stFlrSF         1156.534613
2ndFlrSF          325.967786
LowQualFinSF        3.543523
GrLivArea        1486.045922
BsmtFullBath        0.434454
BsmtHalfBath        0.065202
FullBath            1.570939
HalfBath            0.377656
BedroomAbvGr        2.854010
KitchenAbvGr        1.042495
TotRmsAbvGrd        6.385195
Fireplaces          0.581220
GarageYrBlt      1977.721217
GarageCars          1.766118
GarageArea        472.768861
WoodDeckSF         93.174777
OpenPorchSF        48.313914
EnclosedPorch      24.243317
3SsnPorch           1.794380
ScreenPorch        17.064428
PoolArea            1.744345
MiscVal            58.167923
MoSold              6.104181
YrSold           2007.769705
dtype: float64

In [4]:
#mencari median
median_data = data_frame.median()
median_data

Id               2190.0
MSSubClass         50.0
LotFrontage        67.0
LotArea          9399.0
OverallQual         6.0
OverallCond         5.0
YearBuilt        1973.0
YearRemodAdd     1992.0
MasVnrArea          0.0
BsmtFinSF1        350.5
BsmtFinSF2          0.0
BsmtUnfSF         460.0
TotalBsmtSF       988.0
1stFlrSF         1079.0
2ndFlrSF            0.0
LowQualFinSF        0.0
GrLivArea        1432.0
BsmtFullBath        0.0
BsmtHalfBath        0.0
FullBath            2.0
HalfBath            0.0
BedroomAbvGr        3.0
KitchenAbvGr        1.0
TotRmsAbvGrd        6.0
Fireplaces          0.0
GarageYrBlt      1979.0
GarageCars          2.0
GarageArea        480.0
WoodDeckSF          0.0
OpenPorchSF        28.0
EnclosedPorch       0.0
3SsnPorch           0.0
ScreenPorch         0.0
PoolArea            0.0
MiscVal             0.0
MoSold              6.0
YrSold           2008.0
dtype: float64

In [5]:
# list_median = []
# for  kolom in data_frame.columns:
# #     print(kolom,"=>",type(data_frame[kolom][0]),'!', type(data_frame[kolom][1]))
#     if  type(data_frame[kolom][0]) == type(data_frame['1stFlrSF'][3]):
#         list_median.append(kolom)
        
# len(list_median)

In [6]:
# type(data_frame['1stFlrSF'][3])==type(data_frame['1stFlrSF'][3])

In [7]:
#cek Nama Kolom
print(len(data_frame.columns), "kolom")
data_frame.columns

80 kolom

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition'],
      dtype='object')

In [8]:
#ubah nama kolom menjadi lower
# data_frame.columns= data_frame.columns.str.strip().str.lower()

# data_frame

In [9]:
#proses merubah data menjadi lower
#dan merubah null data menjadi median
for kolom in data_frame.columns:
    try: #yang diubah hanya data yang bertipe string
        data_frame[kolom] = data_frame[kolom].str.lower()
    except: #jika data bukan bertipe string maka akan dilewati (pass)
        data_frame[kolom] = data_frame[kolom].fillna(median_data[kolom])

In [10]:
#hanya buat cek dataframe setelah diubah menjadi lower
data_frame

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,rh,80.0,11622,pave,NaN,reg,lvl,allpub,...,120,0,NaN,mnprv,NaN,0,6,2010,wd,normal
1,1462,20,rl,81.0,14267,pave,NaN,ir1,lvl,allpub,...,0,0,NaN,NaN,gar2,12500,6,2010,wd,normal
2,1463,60,rl,74.0,13830,pave,NaN,ir1,lvl,allpub,...,0,0,NaN,mnprv,NaN,0,3,2010,wd,normal
3,1464,60,rl,78.0,9978,pave,NaN,ir1,lvl,allpub,...,0,0,NaN,NaN,NaN,0,6,2010,wd,normal
4,1465,120,rl,43.0,5005,pave,NaN,ir1,hls,allpub,...,144,0,NaN,NaN,NaN,0,1,2010,wd,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,rm,21.0,1936,pave,NaN,reg,lvl,allpub,...,0,0,NaN,NaN,NaN,0,6,2006,wd,normal
1455,2916,160,rm,21.0,1894,pave,NaN,reg,lvl,allpub,...,0,0,NaN,NaN,NaN,0,4,2006,wd,abnorml
1456,2917,20,rl,160.0,20000,pave,NaN,reg,lvl,allpub,...,0,0,NaN,NaN,NaN,0,9,2006,wd,abnorml
1457,2918,85,rl,62.0,10441,pave,NaN,reg,lvl,allpub,...,0,0,NaN,mnprv,shed,700,7,2006,wd,normal
1458,2919,60,rl,74.0,9627,pave,NaN,reg,lvl,allpub,...,0,0,NaN,NaN,NaN,0,11,2006,wd,normal

In [11]:
#optional, Kalau NA mau tampil
# data_frame = data_frame.fillna("NA")

#memampilkan Data dengan NA
# data_frame

In [12]:
#Simpan data di harddisk
data_frame.to_csv("test_output.csv",index=False)

In [16]:
# set(data_frame.Utilities)

{'allpub', nan}